backend_staff/urls.py
from django.conf.urls import url
from backend_staff.views import (
    IndexView,
    PopularProposalCommentsView,
    ModeratePopularProposalView,
    AcceptPopularProposalView,
    RejectPopularProposalView,
    AddContactAndSendMailView,
    AllCommitmentsView,
    StatsView,
    ListOfUsers,
    StatsPerAreaView,
)

urlpatterns = [
    url(r'^$',
        IndexView.as_view(),
        name='index'),
    url(r'^stats/?$',
        StatsView.as_view(),
        name='stats'),
    url(r'^per_area_stats/?$',
        StatsPerAreaView.as_view(),
        name='per_area_stats'),
    url(r'^popular_proposal_comments/(?P<pk>[-\w]+)/?$',
        PopularProposalCommentsView.as_view(),
        name='popular_proposal_comments'),
    url(r'^moderate_popular_proposal/(?P<pk>[-\w]+)/?$',
        ModeratePopularProposalView.as_view(),
        name='moderate_proposal'),
    url(r'^accept_popular_proposal/(?P<pk>[-\w]+)/?$',
        AcceptPopularProposalView.as_view(),
        name='accept_proposal'),
    url(r'^reject_popular_proposal/(?P<pk>[-\w]+)/?$',
        RejectPopularProposalView.as_view(),
        name='reject_proposal'),
    url(r'^add_contact_and_sen_mail/(?P<pk>[-\w]+)/?$',
        AddContactAndSendMailView.as_view(),
        name='add_contact_and_send_mail'),
    url(r'^all_commitments/?$',
        AllCommitmentsView.as_view(),
        name='all_commitments'),
    url(r'^list_of_users/?$',
        ListOfUsers.as_view(),
        name='list_of_users'),
]

elections/urls.py
from django.conf import settings
from django.conf.urls import url
from haystack.views import SearchView
from elections.forms import ElectionForm
from elections.views import (
    ElectionsSearchByTagView,
    HomeView,
    ElectionDetailView,
    CandidateDetailView,
    FaceToFaceView,
    AreaDetailView,
    CandidateFlatPageDetailView,
    KnowYourCandidatesView,
    )

from elections.soul_mate import SoulMateDetailView

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.cache import cache_page


media_root = getattr(settings, 'MEDIA_ROOT', '/')




urlpatterns = [
    url(r'^$', cache_page(60 * settings.CACHE_MINUTES)(xframe_options_exempt(HomeView.as_view())), name='home'),
    url(r'^buscar/?$', SearchView(template='search.html',
            form_class=ElectionForm), name='search'),
    url(r'^busqueda_tags/?$', ElectionsSearchByTagView.as_view(), name='tags_search'),
    url(r'^eleccion/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_detail.html')),
        name='election_view'),
    url(r'^eleccion/(?P<slug>[-\w]+)/questionary/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_questionary.html')),
        name='questionary_detail_view'),
    #compare two candidates
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/(?P<slug_candidate_two>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(FaceToFaceView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_two_candidates_detail_view'),
    #one candidate for compare
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_one_candidate_detail_view'),
    #no one candidate
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_no_candidate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/soul-mate/?$',
        csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html')),
        name='soul_mate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/embedded-soul-mate/?$',
        xframe_options_exempt(csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html', layout="elections/embedded.html"))),
        name='embedded_soul_mate_detail_view'),

    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view'
        ),
    url(r'^candidaturas/(?P<area_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view_area'
        ),
    # End Preguntales
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<url>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateFlatPageDetailView.as_view()),
        name='candidate_flatpage'
        ),
    url(r'^eleccion/(?P<slug>[-\w]+)/extra_info.html$',
        ElectionDetailView.as_view(template_name='elections/extra_info.html'),
        name='election_extra_info'),
    url(r'^candidaturas/(?P<slug>[-\w]+)/?$',
        AreaDetailView.as_view(template_name='elections/area.html'),
        name='area'),
    url(r'^ayudanos/(?P<slug>[-\w]+)/?$',
        ElectionDetailView.as_view(template_name='elections/ayudanos.html'),
        name='help_election'),
    url(r'^candidaturas/?$', KnowYourCandidatesView.as_view(), name='know_your_candidates'),
    
]

# urlpatterns += [
#     url(r'^cache/(?P<path>.*)$', sitemap,
#         {'document_root': media_root})
# ]

merepresenta/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView, RedirectView
from merepresenta.forms import (MeRepresentaMeiaLaranjaWizardForm,
                                MeRepresentaMeiaLaranjaQuestionsWizardForm)
from elections.views import CandidateDetailView
from elections.models import QuestionCategory
from django.contrib import admin
from backend_candidate.views import CompleteMediaNaranjaView
from backend_candidate.forms import MediaNaranjaElectionForm
from merepresenta.voluntarios.views import (VolunteerIndexView,
                                            VolunteerLoginView,
                                            AddMailToCandidateView,
                                            ObrigadoView,
                                            auth,
                                            CouldNotFindCandidate,
                                            FacebookContacted,
                                            complete)
from merepresenta.match.views import MatchView, MatchResultView, MatchResultAjaxView
from merepresenta.views import ColigacoesPerAreaView, ColigacoesInitialRedirect

class MeRepresentaMeiaLaranjaForm(MediaNaranjaElectionForm):
    def __init__(self, *args, **kwargs):
        self.categories  = QuestionCategory.objects.all()
        super(MeRepresentaMeiaLaranjaForm, self).__init__(*args, **kwargs)

class MeRepresentaMeiaLaranja(CompleteMediaNaranjaView):
    def get_form_class(self):
        return MeRepresentaMeiaLaranjaForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',
        TemplateView.as_view(template_name="merepresenta/index.html"),
        name='index'),

    url(r'^sobre/?$',
        TemplateView.as_view(template_name="merepresenta/sobre.html"),
        name='sobre'),
    url(r'^eleitor/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitores/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitorx/?$',
        TemplateView.as_view(template_name='merepresenta/eleitor.html'),
        name='eleitorx'),
    url(r'^termos/?$',
        TemplateView.as_view(template_name="merepresenta/termos.html"),
        name='termos'),
    url(r'^pautas/?$',
        TemplateView.as_view(template_name="merepresenta/pautas.html"),
        name='pautas'),
    url(r'^coligacoes/?$',
        ColigacoesInitialRedirect.as_view(),
        name='coligacoes_initial'),
    url(r'^coligacoes/(?P<slug>[-\w]+)/?$',
        ColigacoesPerAreaView.as_view(),
        name='coligacoes'),
    url(r'^eleitora/?$',
        MatchView.as_view(),
        name='match'),
    url(r'^resultado/?$',
        MatchResultView.as_view(),
        name='match_result'),
    url(r'^match_result_ajax/?$',
        MatchResultAjaxView.as_view(),
        name='match_result_ajax'),




    url(r'^perguntas/?$',
        MeRepresentaMeiaLaranjaWizardForm.as_view(),
        name='questionary'),
    url(r'^answers/?$',
        MeRepresentaMeiaLaranjaQuestionsWizardForm.as_view(),
        name='questions'),
    url(r'^candidatos/', include('merepresenta.candidatos.urls')),
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        CandidateDetailView.as_view(template_name='merepresenta/candidate_detail.html'),
        name='candidate_detail_view'
        ),
    url(r'^candidatos/media_naranja/(?P<slug>[-\w]+)/(?P<candidate_slug>[-\w]+)/?$',
        MeRepresentaMeiaLaranja.as_view(),
        name='complete_12_naranja'),
    url(r'^candidatos/?', include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^accounts/?', include('registration.backends.hmac.urls')),
    url(r'^voluntarios/', include('merepresenta.voluntarios.urls')),
    url(r'^faq/?$',
    TemplateView.as_view(template_name="merepresenta/faq.html"),
    name='faq'),
]

votainteligente/urls.py
from django.conf.urls import include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from backend_candidate.views import HelpFindingCandidates
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_change, password_change_done, login
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from votainteligente.sitemaps  import ElectionsSitemap, CandidatesSitemap, ProposalSitemap
from votainteligente.rest_api_router import router
from django.utils.translation import ugettext_lazy as _
admin.autodiscover()
admin.site.site_header = getattr(settings, 'ADMIN_HEADER', 'Vota Inteligente')


sitemaps = {
    'elections': ElectionsSitemap,
    'candidates': CandidatesSitemap,
    'proposals': ProposalSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'votainteligente.views.home', name='home'),
    # url(r'^votainteligente/', include('votainteligente.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('elections.urls')),
    url(_(r'^preguntales/'), include('preguntales.urls')),
    url(_(r'^propuestas/'), include('popular_proposal.urls', namespace='popular_proposals')),
    url(_('^pages/'), include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backend_staff/', include('backend_staff.urls', namespace='backend_staff')),
    url(_(r'^perfil_ciudadano/'), include('backend_citizen.urls', namespace='backend_citizen')),
    url(r'^suggestions/', include('suggestions_for_candidates.urls', namespace='suggestions_for_candidates')),
    url(_(r'^media_naranja/'), include('medianaranja2.urls', namespace='medianaranja2')),
    url(_(r'^organizacion/'), include('organization_profiles.urls', namespace='organization_profiles')),
    url(_(r'^candidatos/'), include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^proposal_subscriptions/', include('proposal_subscriptions.urls', namespace='proposal_subscriptions')),
    url(r'^levantalamano/', include('votita.urls', namespace='votita')),
    url(r'^cuentas/', include('votita.urls.auth_urls', namespace="votita_auth")),
    url(_(r'^ayudanos/$'),
        HelpFindingCandidates.as_view(),
        name='help'),
    url(_(r'^encuentro_ciudadano/$'),
        TemplateView.as_view(template_name='encuentro_ciudadano.html'),
        name='encuentro_ciudadano'),
    url(_(r'^que_es/$'),
        TemplateView.as_view(template_name='que_es.html'),
        name='que_es'),
    url(_(r'^material_ciudadano/$'),
        TemplateView.as_view(template_name='material_ciudadano.html'),
        name='material_ciudadano'),
    url(r'^cores/$',
        TemplateView.as_view(template_name='cores.html'),
        name='cores'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/organizacion/?$',
        login,
        {'template_name': 'registration/login_organizacion.html'},
        name='login_users'),
    url(r'^accounts/login/usuario_y_password/?$',
        login,
        {'template_name': 'registration/login_username_and_password.html'},
        name='username_and_password'),
    url(r'^accounts/passwordchange/?$',
        password_change,
        {'template_name': 'registration/password_change.html'},
        name='password_reset'),
    url(r'^accounts/passwordchange/done/?$',
        password_change_done,
        {'template_name': 'registration/password_change_done_.html'},
        name='password_change_done'),
    url(r'^api/', include(router.urls)),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),

]

urlpatterns += [
                        url('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.THEME:
    urlpatterns += [
        url('^theme/', include('%s.urls' % (settings.THEME)))
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

backend_staff/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backend_staff/forms.py
# coding=utf-8
from django import forms
from backend_candidate.models import add_contact_and_send_mail


class AddContactAndSendMailForm(forms.Form):
    mail = forms.EmailField()

    def __init__(self, *args, **kwargs):
        self.candidate = kwargs.pop('candidate')
        super(AddContactAndSendMailForm, self).__init__(*args, **kwargs)

    def send_mail(self):
        add_contact_and_send_mail(self.cleaned_data['mail'], self.candidate)

votai_general_theme/forms.py
# coding=utf-8
from django import forms


class PersonalDataForm(forms.Form):
    age = forms.IntegerField(label='Edad', required=False, initial=0)
    lema = forms.CharField(label=u'Lema de campaña', required=False, initial='')
    partido = forms.CharField(label=u'Partido', required=False, initial='')
    pacto = forms.CharField(label=u'Pacto', required=False, initial='')
    ocupacion = forms.CharField(label=u'Ocupación', required=False, initial='')
    experiencia = forms.CharField(label=u'Reseña Biográfica',
                                  widget=forms.Textarea(),
                                  max_length=4096,
                                  required=False,
                                  initial=''
                                  )
    telefono = forms.CharField(label=u'Teléfono',
                               required=False,
                               initial='',
                               help_text=u"¿Hay algún teléfono donde los ciudadanos interesados en tu campaña se puedan comunicar con tu comando?")

votai_general_theme/templates/backend_staff/add_contact_and_send_mail.html
{% load bootstrap3 %}
{% load static %}
{% load i18n %}

<h5>{% trans "Hermana/o al apretar submit se le enviará un mail al candidato con su nuevo usuario y password" %}</h5>
<form role="form" action="{% url 'backend_staff:add_contact_and_send_mail' pk=candidate.pk %}" method="post">
	{% csrf_token %}
    {% bootstrap_form form%}
        <button class="btn btn-success pull-right" type="submit" value="{% trans "Submit" %}">{% trans "Envía mail" %}<img src="{% static 'img/arrow.svg' %}"></button>
</form>

votai_general_theme/templates/backend_staff/all_commitments.html
{% extends 'backend_base.html' %}
{% load i18n %}
{% block content %}
	<h2>{% blocktrans with commitments_count=commitments.count %}
		Le tenimo {commitments_count{}} compromisos.
	{% endblocktrans %}</h2>
	<ul>
		{% for commitment in commitments %}
		<li>{{commitment.candidate.election}} - {{commitment.candidate}} - <a href="{{commitment.get_absolute_url}}">{{commitment.proposal.title}}</a></li>
		{% endfor %}
	</ul>
{% endblock content%}

votai_general_theme/templates/backend_staff/index.html
{% extends "backend_base.html" %}
{% load staticfiles %}
{% load votainteligente_extras %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}

{% block content %}
{% include 'modal.html' with modalId='proposalComments' title='Actualiza los comentarios' %}
{% include 'modal.html' with modalId='moderateProposal' title='¿Deseas aceptar la Propuesta Popular?' %}

<div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/jquery.gridAccordion.min.js' %}"></script>
  <!-- Featured Elections  -->
  <div class="contenedorDestacado fondo-blanco">
    <h1>{% blocktrans %}¡Terrible de bienvenid@!{% endblocktrans %}</h1>
    <h2>{% blocktrans %}¡Eres parte de nuestro equipo!{% endblocktrans %}</h2>
    <p>{% trans "Aquí podrás ver y moderar los elementos de VotaInteligente " %}</p>

    <table class="table table-striped">
      <thead>
        <tr>
            <th>{% trans "ID" %}</th>
            <th>{% trans "Area" %}</th>
            <th>{% trans "Area" %}</th>
            <th>Problema</th>
            <th>{% trans "+Info" %}</th>
            <th>{% trans "Organización" %}</th>
            <th>{% trans "Usuario" %}</th>
            <th>{% trans "Comentarios del usuario" %}</th>
            <th>{% trans "Acciones" %}</th>
        </tr>
      </thead>
    {% for proposal in proposals.all %}
        {% if proposal.status != 'accepted' %}
        <tr>
            <td>{{proposal.id}}</td>
            <td>{{proposal.area}}</td>
            <td>{{proposal.created}}</td>
            <td>{{proposal.data.problem|truncatechars:100}}{% include 'popular_proposal/_show_proposal_comments.html' with comments=proposal.comments.problem %}
            </td>
            <td>
                <button type="button" class="btn btn-lg btn-danger masInfo" data-toggle="popover" title="+ Info" data-content="{% get_questions_and_descriptions proposal %}">?</button>

            </td>
            <td>
                {{proposal.data.organization}}
                {% include 'popular_proposal/_show_proposal_comments.html' with comments=proposal.comments.organization %}
            </td>
            <td>
                {{proposal.proposer}}
                {% if proposal.proposer|is_candidate %} (candidato){% endif %}
            </td>
            <td>{% if proposal.overall_comments %}<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>{% endif %}
                {{proposal.overall_comments}}
                </td>
            <td>
                {% if proposal.status == 'in_our_side' %}
                <a data-toggle="modal" data-target="#proposalComments"
                    data-url="{% url 'backend_staff:popular_proposal_comments' pk=proposal.id %}">
                    <i class="fa fa-pencil-square-o" title="Editame!"></i>
                </a>
                <a data-toggle="modal" data-target="#moderateProposal"
                    data-url="{% url 'backend_staff:moderate_proposal' pk=proposal.id %}">
                    <i class="fa fa-gavel" title='{% trans "Moderame!" %}'></i>
                </a>
                {% elif proposal.status == 'in_their_side' %}
                <span class="label label-default">{% trans 'Esperando al usuario' %}</span>
                {% elif proposal.status == 'accepted' %}
                <span class="label label-success">{% trans '¡Aceptada!' %}</span>
                {% elif proposal.status == 'in_their_side' %}
                <span class="label label-danger">{% trans '¡Rechazada!' %}</span>
                {% endif %}
            </td>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
  </div>

</div>
<script>
$(function(){
    $('.masInfo').popover({
        'html': true,
        'delay': { "show": 500, "hide": 100 }
    });
})
function accept_moderation(url){
      $.post(url, {
        'csrfmiddlewaretoken': "{{ csrf_token }}"
        }, function(){
            location.reload();
        })
}
</script>
{% endblock content %}

{% block extrafooter %}
{% endblock extrafooter %}

votai_general_theme/templates/backend_staff/list_of_users.html
{% extends "backend_base.html" %}
{% load staticfiles %}
{% load votainteligente_extras %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}

{% block content %}
<h4 class="page-header">Gente da Casa Fluminense</h4>
<h5 class="page-header">Issos sao os usuarios</h5>
<div class="table-responsive">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>Username</th>
          <th>Nome</th>
          <th>email</th>
          <th>é organizacao??????</th>
	  <th>data de criacao</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users.all %}
        <tr>
          <td>{{user.username}}</td>
          <td>{{user.name}}</td>
          <td>{{user.email}}</td>
          <td>{{user.profile.is_organization}}</td>
          <td>{{user.date_joined}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock content %}

{% block extrafooter %}
{% endblock extrafooter %}

votai_general_theme/templates/backend_staff/per_area_stats.html
{% extends "backend_base.html" %}
{% load staticfiles %}
{% load votainteligente_extras %}
{% load i18n %}
{% load thumbnail %}
{% load cache %}
{% load bootstrap3 %}

{% block content %}
<h1>{% trans "Las instituciones van a intentar preservar el problema para el cual ellas son la solución" %}</h1>
<h2>{% trans "Los números por comuna:" %}</h2>

<div class="table-responsive">
  <table class="table table-striped">
  	<thead>
      <tr>
        <th>{% trans "Comuna" %}</th>
        <th>{% trans "Promesas Ciudadanas locales" %}</th>
        <th>{% trans "Promesas Ciudadanas totales" %}</th>
        <th>{% trans "Compromisos" %}</th>
        <th>{% trans "Candidatos" %}</th>
      </tr>
    </thead>
    <tbody>
    {% cache 500 comunas %}
    {% for id, stats_per_area in stats.items %}
      {% if stats_per_area.area.candidates.count %}
      <tr class="{% if stats_per_area.area|is_marked_area %}success{% endif %}">
        <td><a href="{{ stats_per_area.area.get_absolute_url }}">{{ stats_per_area.area }}</a></td>
        <td>{{ stats_per_area.proposals__for_all_areas__.count }}</td>
        <td>{{ stats_per_area.proposals.count }}</td>
        <td>{{ stats_per_area.commitments.count }}</td>
        <td>{{stats_per_area.commiters.count}}/ {{stats_per_area.area.candidates.count}}</td>
        <!--td>{{stats_per_area.candidates_that_have_12_naranja__alcalde.count}}/{{stats_per_area.total_candidates__alcalde.count}}</td>
        <td>{{stats_per_area.candidates_that_have_12_naranja__concejal.count}}/{{stats_per_area.total_candidates__concejal.count}}</td-->
      </tr>
      {% endif %}
    {% endfor %}
    {% endcache %}
    </tbody>
  </table>
 </div>
{% endblock content %}

votai_general_theme/templates/backend_staff/popular_proposal_comments.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}

<form action="{% url 'backend_staff:popular_proposal_comments' pk=temporary_data.id %}" method="POST" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{% trans 'Envía estos comentarios a su autor'%}</button>
    </div>
</form>

votai_general_theme/templates/backend_staff/proposal_moderation.html
{% load i18n %}
{% load bootstrap3 %}
   {{object}}

   <button id="acceptModeration_{{object.id}}" onclick='accept_moderation("{% url 'backend_staff:accept_proposal' pk=object.pk %}")'type="button" class="btn btn-primary">{% trans 'Sí, acepto' %} <i class="fa fa-thumbs-up"></i>
</button>
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
 {% trans 'No, la rechazaré!' %} <i class="fa fa-thumbs-down"></i>
</button>
<div class="collapse" id="collapseExample">
  <div class="well">
  <form role="form" action="{% url 'backend_staff:reject_proposal' pk=object.pk %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{% trans 'Rechaza esta propuesta ciudadana'%}</button>
    </div>
</form>
  </div>
</div>