elections/urls.py
from django.conf import settings
from django.conf.urls import url
from haystack.views import SearchView
from elections.forms import ElectionForm
from elections.views import (
    ElectionsSearchByTagView,
    HomeView,
    ElectionDetailView,
    CandidateDetailView,
    FaceToFaceView,
    AreaDetailView,
    CandidateFlatPageDetailView,
    KnowYourCandidatesView,
    )

from elections.soul_mate import SoulMateDetailView

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.cache import cache_page


media_root = getattr(settings, 'MEDIA_ROOT', '/')




urlpatterns = [
    url(r'^$', cache_page(60 * settings.CACHE_MINUTES)(xframe_options_exempt(HomeView.as_view())), name='home'),
    url(r'^buscar/?$', SearchView(template='search.html',
            form_class=ElectionForm), name='search'),
    url(r'^busqueda_tags/?$', ElectionsSearchByTagView.as_view(), name='tags_search'),
    url(r'^eleccion/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_detail.html')),
        name='election_view'),
    url(r'^eleccion/(?P<slug>[-\w]+)/questionary/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_questionary.html')),
        name='questionary_detail_view'),
    #compare two candidates
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/(?P<slug_candidate_two>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(FaceToFaceView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_two_candidates_detail_view'),
    #one candidate for compare
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_one_candidate_detail_view'),
    #no one candidate
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_no_candidate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/soul-mate/?$',
        csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html')),
        name='soul_mate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/embedded-soul-mate/?$',
        xframe_options_exempt(csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html', layout="elections/embedded.html"))),
        name='embedded_soul_mate_detail_view'),

    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view'
        ),
    url(r'^candidaturas/(?P<area_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view_area'
        ),
    # End Preguntales
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<url>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateFlatPageDetailView.as_view()),
        name='candidate_flatpage'
        ),
    url(r'^eleccion/(?P<slug>[-\w]+)/extra_info.html$',
        ElectionDetailView.as_view(template_name='elections/extra_info.html'),
        name='election_extra_info'),
    url(r'^candidaturas/(?P<slug>[-\w]+)/?$',
        AreaDetailView.as_view(template_name='elections/area.html'),
        name='area'),
    url(r'^ayudanos/(?P<slug>[-\w]+)/?$',
        ElectionDetailView.as_view(template_name='elections/ayudanos.html'),
        name='help_election'),
    url(r'^candidaturas/?$', KnowYourCandidatesView.as_view(), name='know_your_candidates'),
    
]

# urlpatterns += [
#     url(r'^cache/(?P<path>.*)$', sitemap,
#         {'document_root': media_root})
# ]

merepresenta/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView, RedirectView
from merepresenta.forms import (MeRepresentaMeiaLaranjaWizardForm,
                                MeRepresentaMeiaLaranjaQuestionsWizardForm)
from elections.views import CandidateDetailView
from elections.models import QuestionCategory
from django.contrib import admin
from backend_candidate.views import CompleteMediaNaranjaView
from backend_candidate.forms import MediaNaranjaElectionForm
from merepresenta.voluntarios.views import (VolunteerIndexView,
                                            VolunteerLoginView,
                                            AddMailToCandidateView,
                                            ObrigadoView,
                                            auth,
                                            CouldNotFindCandidate,
                                            FacebookContacted,
                                            complete)
from merepresenta.match.views import MatchView, MatchResultView, MatchResultAjaxView
from merepresenta.views import ColigacoesPerAreaView, ColigacoesInitialRedirect

class MeRepresentaMeiaLaranjaForm(MediaNaranjaElectionForm):
    def __init__(self, *args, **kwargs):
        self.categories  = QuestionCategory.objects.all()
        super(MeRepresentaMeiaLaranjaForm, self).__init__(*args, **kwargs)

class MeRepresentaMeiaLaranja(CompleteMediaNaranjaView):
    def get_form_class(self):
        return MeRepresentaMeiaLaranjaForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',
        TemplateView.as_view(template_name="merepresenta/index.html"),
        name='index'),

    url(r'^sobre/?$',
        TemplateView.as_view(template_name="merepresenta/sobre.html"),
        name='sobre'),
    url(r'^eleitor/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitores/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitorx/?$',
        TemplateView.as_view(template_name='merepresenta/eleitor.html'),
        name='eleitorx'),
    url(r'^termos/?$',
        TemplateView.as_view(template_name="merepresenta/termos.html"),
        name='termos'),
    url(r'^pautas/?$',
        TemplateView.as_view(template_name="merepresenta/pautas.html"),
        name='pautas'),
    url(r'^coligacoes/?$',
        ColigacoesInitialRedirect.as_view(),
        name='coligacoes_initial'),
    url(r'^coligacoes/(?P<slug>[-\w]+)/?$',
        ColigacoesPerAreaView.as_view(),
        name='coligacoes'),
    url(r'^eleitora/?$',
        MatchView.as_view(),
        name='match'),
    url(r'^resultado/?$',
        MatchResultView.as_view(),
        name='match_result'),
    url(r'^match_result_ajax/?$',
        MatchResultAjaxView.as_view(),
        name='match_result_ajax'),




    url(r'^perguntas/?$',
        MeRepresentaMeiaLaranjaWizardForm.as_view(),
        name='questionary'),
    url(r'^answers/?$',
        MeRepresentaMeiaLaranjaQuestionsWizardForm.as_view(),
        name='questions'),
    url(r'^candidatos/', include('merepresenta.candidatos.urls')),
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        CandidateDetailView.as_view(template_name='merepresenta/candidate_detail.html'),
        name='candidate_detail_view'
        ),
    url(r'^candidatos/media_naranja/(?P<slug>[-\w]+)/(?P<candidate_slug>[-\w]+)/?$',
        MeRepresentaMeiaLaranja.as_view(),
        name='complete_12_naranja'),
    url(r'^candidatos/?', include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^accounts/?', include('registration.backends.hmac.urls')),
    url(r'^voluntarios/', include('merepresenta.voluntarios.urls')),
    url(r'^faq/?$',
    TemplateView.as_view(template_name="merepresenta/faq.html"),
    name='faq'),
]

popular_proposal/urls.py
from django.conf.urls import url
from popular_proposal.views.proposal_views import (ProposalCreationView,
                                                   ThanksForProposingView,
                                                   SubscriptionView,
                                                   HomeView,
                                                   PopularProposalDetailView,
                                                   PopularProposalUpdateView,
                                                   UnlikeProposalView,
                                                   ProposalsPerArea,
                                                   CommitView,
                                                   NotCommitView,
                                                   CommitmentDetailView,
                                                   PopularProposalOGImageView,
                                                   PopularProposalDetailRedirectView,
                                                   PopularProposalAyuranosView,
                                                   )
from popular_proposal.views.wizard import (ProposalWizard,
                                           ProposalWizardFull,
                                           ProposalWizardFullWithoutArea,
                                           wizard_creator_chooser)
from django.views.decorators.clickjacking import xframe_options_exempt
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^$',
        HomeView.as_view(),
        name='home'),
    url(r'^embedded/?$',
        xframe_options_exempt(HomeView.as_view(is_embedded=True)),
        name='embedded_home'),
    url(r'^area_embedded/(?P<slug>[-\w]+)/?$',
        xframe_options_exempt(ProposalsPerArea.as_view(is_embedded=True)),
        name='area_embedded'),
    url(r'^create_wizard/(?P<slug>[-\w]+)/?$',
        ProposalWizard.as_view(),
        name='propose_wizard'),
    url(_(r'^nueva/?$'),
        ProposalWizardFull.as_view(),
        name='propose_wizard_full'),
    url(_(r'^crear/?$'),
        wizard_creator_chooser().as_view(),
        name='propose_wizard_full_without_area'),
    url(r'^detail/(?P<slug>[-\w]+)/?$',
        xframe_options_exempt(PopularProposalDetailView.as_view()),
        name='detail'),
    url(_(r'^ayudanos/(?P<slug>[-\w]+)/?$'),
        PopularProposalAyuranosView.as_view(),
        name='ayuranos'),
    url(r'^d/(?P<pk>\d+)/?$',
        PopularProposalDetailRedirectView.as_view(),
        name='short_detail'),
    url(r'^og_image/(?P<slug>[-\w]+).jpg$',
        PopularProposalOGImageView.as_view(),
        name='og_image'),
    url(_(r'^commitment/(?P<candidate_slug>[-\w]+)/(?P<proposal_slug>[-\w]+)/?$'),
        CommitmentDetailView.as_view(),
        name='commitment'),
    url(_(r'^commit/(?P<candidate_pk>[-\w]+)/(?P<proposal_pk>\d+)/?$'),
        CommitView.as_view(),
        name='commit_yes'),
    url(_(r'^not_commit/(?P<candidate_pk>[-\w]+)/(?P<proposal_pk>\d+)/?$'),
        NotCommitView.as_view(),
        name='commit_no'),
    url(r'^embedded_detail/(?P<slug>[-\w]+)/?$',
        xframe_options_exempt(PopularProposalDetailView.as_view(is_embedded=True)),
        name='embedded_detail'),
    url(_(r'^unlike/(?P<pk>\d+)/?$'),
        UnlikeProposalView.as_view(),
        name='unlike_proposal'),
    url(_(r'^actualizar/(?P<slug>[-\w]+)/?$'),
        PopularProposalUpdateView.as_view(),
        name='citizen_update'),
    url(r'^(?P<slug>[-\w]+)/?$',
        ProposalCreationView.as_view(),
        name='propose'),
    url(_(r'^(?P<pk>[-\w]+)/gracias/?$'),
        ThanksForProposingView.as_view(),
        name='thanks'),
    url(_(r'^(?P<pk>[-\w]+)/subscribe/?$'),
        SubscriptionView.as_view(),
        name='like_a_proposal'),
]

votainteligente/urls.py
from django.conf.urls import include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from backend_candidate.views import HelpFindingCandidates
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_change, password_change_done, login
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from votainteligente.sitemaps  import ElectionsSitemap, CandidatesSitemap, ProposalSitemap
from votainteligente.rest_api_router import router
from django.utils.translation import ugettext_lazy as _
admin.autodiscover()
admin.site.site_header = getattr(settings, 'ADMIN_HEADER', 'Vota Inteligente')


sitemaps = {
    'elections': ElectionsSitemap,
    'candidates': CandidatesSitemap,
    'proposals': ProposalSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'votainteligente.views.home', name='home'),
    # url(r'^votainteligente/', include('votainteligente.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('elections.urls')),
    url(_(r'^preguntales/'), include('preguntales.urls')),
    url(_(r'^propuestas/'), include('popular_proposal.urls', namespace='popular_proposals')),
    url(_('^pages/'), include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backend_staff/', include('backend_staff.urls', namespace='backend_staff')),
    url(_(r'^perfil_ciudadano/'), include('backend_citizen.urls', namespace='backend_citizen')),
    url(r'^suggestions/', include('suggestions_for_candidates.urls', namespace='suggestions_for_candidates')),
    url(_(r'^media_naranja/'), include('medianaranja2.urls', namespace='medianaranja2')),
    url(_(r'^organizacion/'), include('organization_profiles.urls', namespace='organization_profiles')),
    url(_(r'^candidatos/'), include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^proposal_subscriptions/', include('proposal_subscriptions.urls', namespace='proposal_subscriptions')),
    url(r'^levantalamano/', include('votita.urls', namespace='votita')),
    url(r'^cuentas/', include('votita.urls.auth_urls', namespace="votita_auth")),
    url(_(r'^ayudanos/$'),
        HelpFindingCandidates.as_view(),
        name='help'),
    url(_(r'^encuentro_ciudadano/$'),
        TemplateView.as_view(template_name='encuentro_ciudadano.html'),
        name='encuentro_ciudadano'),
    url(_(r'^que_es/$'),
        TemplateView.as_view(template_name='que_es.html'),
        name='que_es'),
    url(_(r'^material_ciudadano/$'),
        TemplateView.as_view(template_name='material_ciudadano.html'),
        name='material_ciudadano'),
    url(r'^cores/$',
        TemplateView.as_view(template_name='cores.html'),
        name='cores'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/organizacion/?$',
        login,
        {'template_name': 'registration/login_organizacion.html'},
        name='login_users'),
    url(r'^accounts/login/usuario_y_password/?$',
        login,
        {'template_name': 'registration/login_username_and_password.html'},
        name='username_and_password'),
    url(r'^accounts/passwordchange/?$',
        password_change,
        {'template_name': 'registration/password_change.html'},
        name='password_reset'),
    url(r'^accounts/passwordchange/done/?$',
        password_change_done,
        {'template_name': 'registration/password_change_done_.html'},
        name='password_change_done'),
    url(r'^api/', include(router.urls)),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),

]

urlpatterns += [
                        url('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.THEME:
    urlpatterns += [
        url('^theme/', include('%s.urls' % (settings.THEME)))
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

votai_general_theme/forms.py
# coding=utf-8
from django import forms


class PersonalDataForm(forms.Form):
    age = forms.IntegerField(label='Edad', required=False, initial=0)
    lema = forms.CharField(label=u'Lema de campaña', required=False, initial='')
    partido = forms.CharField(label=u'Partido', required=False, initial='')
    pacto = forms.CharField(label=u'Pacto', required=False, initial='')
    ocupacion = forms.CharField(label=u'Ocupación', required=False, initial='')
    experiencia = forms.CharField(label=u'Reseña Biográfica',
                                  widget=forms.Textarea(),
                                  max_length=4096,
                                  required=False,
                                  initial=''
                                  )
    telefono = forms.CharField(label=u'Teléfono',
                               required=False,
                               initial='',
                               help_text=u"¿Hay algún teléfono donde los ciudadanos interesados en tu campaña se puedan comunicar con tu comando?")

votai_general_theme/templates/popular_proposal/commitment/commit_no.html
{% extends 'base.html' %}
{% load votainteligente_extras %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}

{% block extrajs %}
{% load ogp_tags %}
{% endblock extrajs %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans "VotaInteligente" %}</a></li>
    {% if proposal.area %}
      <li><a href="{{proposal.area.get_absolute_url}}">{{proposal.area}}</a></li>
    {% endif %}
    <li><a href="{{proposal.get_absolute_url}}">{{proposal.title}}</a></li>
    <li class="active">{% trans "No lo incluiré" %}</li>
  </ol>
</div>
<div class="container">
	<div class="fondo-blanco text-width">

    {% blocktrans with candidate_name=candidate.name position=candidate.election.position area=proposal.area proposal=proposal.title %}
    Yo <strong>{{candidate_name}}</strong> candidata/o a {{position}} de {{area}} <strong>NO</strong> me comprometo con la propuesta ciudadana <strong>{{proposal}}</strong>.
    {% endblocktrans %}


		<p>{% trans "Por las razones que explicaré a continuación:" %}</p>






	<form enctype="multipart/form-data" action="{% url 'popular_proposals:commit_no' proposal_pk=proposal.id candidate_pk=candidate.id %}" method="POST" role="form">{% csrf_token %}

		{% bootstrap_field form.detail show_label=false %}
	    <div class="tips">
		  <b class="main-title">{% trans "Terminos y Condiciones" %}</b>
		  {% include 'popular_proposal/commitment/terms_and_conditions.html' %}
		</div>
		{% bootstrap_field form.terms_and_conditions show_label=false %}
		<button type="submit" class="btn btn-dark">

			{% if candidate.election.position == 'concejal' %}
				{% trans 'No apoyaré esta propuesta'%}
			{% elif candidate.election.position == 'alcalde' %}
				{% trans 'No incluiré esta propuesta en mi programa'%}
			{% else %}
			{% trans 'No incluiré esta propuesta en mi programa'%}
			{% endif %}
			</button>
	</form>
	</div>
</div>
{% endblock content %}

votai_general_theme/templates/popular_proposal/commitment/commit_yes.html
{% extends 'base.html' %}
{% load votainteligente_extras %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}
{% block title %} - {% trans "Firma Compromiso" %} - {{candidate.name}} - {{proposal.title}}{% endblock title%}
{% block extrajs %}
{% load ogp_tags %}
{% endblock extrajs %}
{% block content %}
<div class="container">
  <ul class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans "VotaInteligente" %}</a></li>
    <li><a href="{% url 'popular_proposals:home' %}">{% trans "Propuestas" %}</a></li>
    <li><a href="{{proposal.get_absolute_url}}">{{proposal.title}}</a></li>
    <li class="active">{% trans "Firmar compromiso" %}</li>
  </ul>
</div>
<div class="container">
  <div class="fondo-blanco text-width">
    <h1>{% trans "Firmar Compromiso" %}</h1>
    <p>{% blocktrans with candidate_name=candidate.name position=candidate.election.position %}
      Yo <strong>{{candidate_name}}</strong>, <strong>{{position}}</strong> me comprometo con la propuesta ciudadana:
    {% endblocktrans %}</p>

    {% include 'popular_proposal/plantillas/candidate_commitment.html' with proposal=proposal %}

    <form enctype="multipart/form-data" action="{% url 'popular_proposals:commit_yes' proposal_pk=proposal.id candidate_pk=candidate.id %}" method="POST" role="form">{% csrf_token %}
      {% bootstrap_field form.detail %}
      <div class="tips">
        <b class="main-title">{% trans "Terminos y Condicione" %}</b>
        {% include 'popular_proposal/commitment/terms_and_conditions.html' %}
      </div>
      {% bootstrap_field form.terms_and_conditions show_label=false %}
      <button type="submit" class="btn btn-success" onclick="ga('send','event','firma-compromiso','click')">{% trans 'Firmar compromiso'%}</button>
    </form>
  </div>
</div>
{% endblock content %}

votai_general_theme/templates/popular_proposal/commitment/detail_yes.html
{% extends 'base.html' %}
{% load votainteligente_extras %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}
{% load ogp_tags %}

{% block title %} - {% trans "Compromiso final" %} - {{commitment.candidate.name}} - {{commitment.proposal.title}}{% endblock title%}

{% block ogp %}
  {% render_ogp popular_proposal %}
  <meta property="og:title" content="{% trans 'En votainteligente.cl revisa el compromiso que he firmado' %}">
  <meta property="og:type" content="{{ config.WEBSITE_OGP_TYPE }}">
  <meta property="og:url" content="https://{% url_domain %}{% url 'popular_proposals:commitment' commitment.candidate.id commitment.proposal.slug %}">
  <meta property="og:image" content="{{commitment.proposal.ogp_image}}">
  <meta property="og:description" content="{% blocktrans with candidate_name=commitment.candidate.name proposal=commitment.proposal.title %}Yo, {{candidate_name}}, me he comprometido con la Propuesta Ciudadana: {{proposal}}{% endblocktrans %}">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@ciudadanoi">
  <meta name="twitter:creator" content="@ciudadanoi">
  <meta name="twitter:title" content="{% trans 'En votainteligente.cl revisa el compromiso que he firmado!' %}">
  <meta name="twitter:description" content="{% blocktrans with candidate_name=commitment.candidate.name proposal=commitment.proposal.title %}Yo, {{candidate_name}}, me he comprometido con la Propuesta Ciudadana: {{proposal}}{% endblocktrans %}">
  <meta name="twitter:image" content="{{commitment.proposal.ogp_image}}">
{% endblock ogp %}

{% block extrajs %}
  {% load ogp_tags %}
{% endblock extrajs %}

{% block content %}
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="{% url 'home' %}"><i class="fa fa-home" aria-label="{% trans 'Inicio' %}"></i></a></li>
      <li><a href="{% url 'popular_proposals:home' %}">{% trans "Propuestas" %}</a></li>
      <li><a href="{{commitment.proposal.get_absolute_url}}">{{commitment.proposal.title}}</a></li>
      <li class="active">{% trans "Compromiso" %}</li>
    </ul>
  </div>
  <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}default{% endif %}">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <p>{{ message }}</p>
        </div>
      {% endfor %}
    {% endif %}
    <h1 class="page-header">{% trans "Compromiso" %}</h1>
    {% blocktrans with candidate_name=commitment.candidate.name %}
    Yo <b>{{candidate_name}}</b> me comprometo con la propuesta ciudadana:
    {% endblocktrans %}

    {% include 'popular_proposal/plantillas/candidate_commitment.html' with proposal=commitment.proposal detail=commitment.detail %}

    <div class="pull-right">
      <p><b>{{commitment.candidate.name}}</b></p>
      <p>{{commitment.candidate.election.position|title }} por {{commitment.candidate.election.area}}.</p>
    </div>
</div>
{% if user|manages_this:commitment.candidate %}
<div class="container text-center">
  <h3>{% trans "Hazlo público!" %}</h3>
  <p>{% trans "Cuéntales a tus futuros electores el compromiso que acabas de firmar!" %}</p>
  <ul class="list-inline">
    <li><a href="#" onclick="window.open('https://twitter.com/share?text={% blocktrans with proposal=commitment.proposal.title %}Me he comprometido con la propuesta ciudadana: {{proposal}}{% endblocktrans %}','twitter','width=450, height=250'); ga('send','event','compartir-compromiso-tw','click')"><i class="fa fa-twitter fa-2x"></i></a></li>
    <li><a href="#" onclick="window.open('https://facebook.com/sharer/sharer.php?u=https://{% url_domain %}{% url 'popular_proposals:commitment' commitment.candidate.id commitment.proposal.slug %}','facebook','width=450, height=250'); ga('send','event','compartir-compromiso-fb','click')"><i class="fa fa-facebook fa-2x"></i></a></li>
  </ul>
</div>
{% else %}
<div class="container text-center">
  <h3>{% trans "Comunícalo!" %}</h3>
  <p>{% trans "Cuéntales a tus amigos sobre este compromiso!" %}</p>
  <ul class="list-inline">
    <li><a href="#" onclick="window.open('https://twitter.com/share?text={% blocktrans with candidate_name=commitment.candidate.name proposal=commitment.proposal.title %}{{candidate_name}} se comprometió con la propuesta ciudadana: {{proposal}}{% endblocktrans %}','twitter','width=450, height=250'); ga('send','event','compartir-compromiso-tw','click')"><i class="fa fa-twitter fa-2x"></i></a></li>
    <li><a href="#" onclick="window.open('https://facebook.com/sharer/sharer.php?u=https://{% url_domain %}{% url 'popular_proposals:commitment' commitment.candidate.id commitment.proposal.slug %}','facebook','width=450, height=250'); ga('send','event','compartir-compromiso-fb','click')"><i class="fa fa-facebook fa-2x"></i></a></li>
  </ul>
</div>
{% endif %}
{% endblock content %}

votai_general_theme/templates/popular_proposal/commitment/terms_and_conditions.html
{% load i18n %}
{% blocktrans %}
<p>La Fundación Ciudadano Inteligente es una ONG sin fines de lucro que busca fortalecer las democracias en América Latina.</p>
<p>Al comprometerme con la propuesta, yo candidata/o, autorizo a Fundación Ciudadano Inteligente a notificar a todos los adherentes. Además autorizo a que  este compromiso sea utilizado como insumo para los medios de comunicación según se estime conveniente.</p>
{% endblocktrans %}