elections/urls.py
from django.conf import settings
from django.conf.urls import url
from haystack.views import SearchView
from elections.forms import ElectionForm
from elections.views import (
    ElectionsSearchByTagView,
    HomeView,
    ElectionDetailView,
    CandidateDetailView,
    FaceToFaceView,
    AreaDetailView,
    CandidateFlatPageDetailView,
    KnowYourCandidatesView,
    )

from elections.soul_mate import SoulMateDetailView

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.cache import cache_page


media_root = getattr(settings, 'MEDIA_ROOT', '/')




urlpatterns = [
    url(r'^$', cache_page(60 * settings.CACHE_MINUTES)(xframe_options_exempt(HomeView.as_view())), name='home'),
    url(r'^buscar/?$', SearchView(template='search.html',
            form_class=ElectionForm), name='search'),
    url(r'^busqueda_tags/?$', ElectionsSearchByTagView.as_view(), name='tags_search'),
    url(r'^eleccion/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_detail.html')),
        name='election_view'),
    url(r'^eleccion/(?P<slug>[-\w]+)/questionary/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_questionary.html')),
        name='questionary_detail_view'),
    #compare two candidates
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/(?P<slug_candidate_two>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(FaceToFaceView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_two_candidates_detail_view'),
    #one candidate for compare
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_one_candidate_detail_view'),
    #no one candidate
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_no_candidate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/soul-mate/?$',
        csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html')),
        name='soul_mate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/embedded-soul-mate/?$',
        xframe_options_exempt(csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html', layout="elections/embedded.html"))),
        name='embedded_soul_mate_detail_view'),

    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view'
        ),
    url(r'^candidaturas/(?P<area_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view_area'
        ),
    # End Preguntales
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<url>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateFlatPageDetailView.as_view()),
        name='candidate_flatpage'
        ),
    url(r'^eleccion/(?P<slug>[-\w]+)/extra_info.html$',
        ElectionDetailView.as_view(template_name='elections/extra_info.html'),
        name='election_extra_info'),
    url(r'^candidaturas/(?P<slug>[-\w]+)/?$',
        AreaDetailView.as_view(template_name='elections/area.html'),
        name='area'),
    url(r'^ayudanos/(?P<slug>[-\w]+)/?$',
        ElectionDetailView.as_view(template_name='elections/ayudanos.html'),
        name='help_election'),
    url(r'^candidaturas/?$', KnowYourCandidatesView.as_view(), name='know_your_candidates'),
    
]

# urlpatterns += [
#     url(r'^cache/(?P<path>.*)$', sitemap,
#         {'document_root': media_root})
# ]

merepresenta/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView, RedirectView
from merepresenta.forms import (MeRepresentaMeiaLaranjaWizardForm,
                                MeRepresentaMeiaLaranjaQuestionsWizardForm)
from elections.views import CandidateDetailView
from elections.models import QuestionCategory
from django.contrib import admin
from backend_candidate.views import CompleteMediaNaranjaView
from backend_candidate.forms import MediaNaranjaElectionForm
from merepresenta.voluntarios.views import (VolunteerIndexView,
                                            VolunteerLoginView,
                                            AddMailToCandidateView,
                                            ObrigadoView,
                                            auth,
                                            CouldNotFindCandidate,
                                            FacebookContacted,
                                            complete)
from merepresenta.match.views import MatchView, MatchResultView, MatchResultAjaxView
from merepresenta.views import ColigacoesPerAreaView, ColigacoesInitialRedirect

class MeRepresentaMeiaLaranjaForm(MediaNaranjaElectionForm):
    def __init__(self, *args, **kwargs):
        self.categories  = QuestionCategory.objects.all()
        super(MeRepresentaMeiaLaranjaForm, self).__init__(*args, **kwargs)

class MeRepresentaMeiaLaranja(CompleteMediaNaranjaView):
    def get_form_class(self):
        return MeRepresentaMeiaLaranjaForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',
        TemplateView.as_view(template_name="merepresenta/index.html"),
        name='index'),

    url(r'^sobre/?$',
        TemplateView.as_view(template_name="merepresenta/sobre.html"),
        name='sobre'),
    url(r'^eleitor/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitores/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitorx/?$',
        TemplateView.as_view(template_name='merepresenta/eleitor.html'),
        name='eleitorx'),
    url(r'^termos/?$',
        TemplateView.as_view(template_name="merepresenta/termos.html"),
        name='termos'),
    url(r'^pautas/?$',
        TemplateView.as_view(template_name="merepresenta/pautas.html"),
        name='pautas'),
    url(r'^coligacoes/?$',
        ColigacoesInitialRedirect.as_view(),
        name='coligacoes_initial'),
    url(r'^coligacoes/(?P<slug>[-\w]+)/?$',
        ColigacoesPerAreaView.as_view(),
        name='coligacoes'),
    url(r'^eleitora/?$',
        MatchView.as_view(),
        name='match'),
    url(r'^resultado/?$',
        MatchResultView.as_view(),
        name='match_result'),
    url(r'^match_result_ajax/?$',
        MatchResultAjaxView.as_view(),
        name='match_result_ajax'),




    url(r'^perguntas/?$',
        MeRepresentaMeiaLaranjaWizardForm.as_view(),
        name='questionary'),
    url(r'^answers/?$',
        MeRepresentaMeiaLaranjaQuestionsWizardForm.as_view(),
        name='questions'),
    url(r'^candidatos/', include('merepresenta.candidatos.urls')),
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        CandidateDetailView.as_view(template_name='merepresenta/candidate_detail.html'),
        name='candidate_detail_view'
        ),
    url(r'^candidatos/media_naranja/(?P<slug>[-\w]+)/(?P<candidate_slug>[-\w]+)/?$',
        MeRepresentaMeiaLaranja.as_view(),
        name='complete_12_naranja'),
    url(r'^candidatos/?', include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^accounts/?', include('registration.backends.hmac.urls')),
    url(r'^voluntarios/', include('merepresenta.voluntarios.urls')),
    url(r'^faq/?$',
    TemplateView.as_view(template_name="merepresenta/faq.html"),
    name='faq'),
]

votainteligente/urls.py
from django.conf.urls import include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from backend_candidate.views import HelpFindingCandidates
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_change, password_change_done, login
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from votainteligente.sitemaps  import ElectionsSitemap, CandidatesSitemap, ProposalSitemap
from votainteligente.rest_api_router import router
from django.utils.translation import ugettext_lazy as _
admin.autodiscover()
admin.site.site_header = getattr(settings, 'ADMIN_HEADER', 'Vota Inteligente')


sitemaps = {
    'elections': ElectionsSitemap,
    'candidates': CandidatesSitemap,
    'proposals': ProposalSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'votainteligente.views.home', name='home'),
    # url(r'^votainteligente/', include('votainteligente.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('elections.urls')),
    url(_(r'^preguntales/'), include('preguntales.urls')),
    url(_(r'^propuestas/'), include('popular_proposal.urls', namespace='popular_proposals')),
    url(_('^pages/'), include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backend_staff/', include('backend_staff.urls', namespace='backend_staff')),
    url(_(r'^perfil_ciudadano/'), include('backend_citizen.urls', namespace='backend_citizen')),
    url(r'^suggestions/', include('suggestions_for_candidates.urls', namespace='suggestions_for_candidates')),
    url(_(r'^media_naranja/'), include('medianaranja2.urls', namespace='medianaranja2')),
    url(_(r'^organizacion/'), include('organization_profiles.urls', namespace='organization_profiles')),
    url(_(r'^candidatos/'), include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^proposal_subscriptions/', include('proposal_subscriptions.urls', namespace='proposal_subscriptions')),
    url(r'^levantalamano/', include('votita.urls', namespace='votita')),
    url(r'^cuentas/', include('votita.urls.auth_urls', namespace="votita_auth")),
    url(_(r'^ayudanos/$'),
        HelpFindingCandidates.as_view(),
        name='help'),
    url(_(r'^encuentro_ciudadano/$'),
        TemplateView.as_view(template_name='encuentro_ciudadano.html'),
        name='encuentro_ciudadano'),
    url(_(r'^que_es/$'),
        TemplateView.as_view(template_name='que_es.html'),
        name='que_es'),
    url(_(r'^material_ciudadano/$'),
        TemplateView.as_view(template_name='material_ciudadano.html'),
        name='material_ciudadano'),
    url(r'^cores/$',
        TemplateView.as_view(template_name='cores.html'),
        name='cores'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/organizacion/?$',
        login,
        {'template_name': 'registration/login_organizacion.html'},
        name='login_users'),
    url(r'^accounts/login/usuario_y_password/?$',
        login,
        {'template_name': 'registration/login_username_and_password.html'},
        name='username_and_password'),
    url(r'^accounts/passwordchange/?$',
        password_change,
        {'template_name': 'registration/password_change.html'},
        name='password_reset'),
    url(r'^accounts/passwordchange/done/?$',
        password_change_done,
        {'template_name': 'registration/password_change_done_.html'},
        name='password_change_done'),
    url(r'^api/', include(router.urls)),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),

]

urlpatterns += [
                        url('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.THEME:
    urlpatterns += [
        url('^theme/', include('%s.urls' % (settings.THEME)))
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

votai_general_theme/forms.py
# coding=utf-8
from django import forms


class PersonalDataForm(forms.Form):
    age = forms.IntegerField(label='Edad', required=False, initial=0)
    lema = forms.CharField(label=u'Lema de campaña', required=False, initial='')
    partido = forms.CharField(label=u'Partido', required=False, initial='')
    pacto = forms.CharField(label=u'Pacto', required=False, initial='')
    ocupacion = forms.CharField(label=u'Ocupación', required=False, initial='')
    experiencia = forms.CharField(label=u'Reseña Biográfica',
                                  widget=forms.Textarea(),
                                  max_length=4096,
                                  required=False,
                                  initial=''
                                  )
    telefono = forms.CharField(label=u'Teléfono',
                               required=False,
                               initial='',
                               help_text=u"¿Hay algún teléfono donde los ciudadanos interesados en tu campaña se puedan comunicar con tu comando?")

votai_general_theme/templates/votita/_footer.html
{% load staticfiles %}
{% load votainteligente_extras %}
<section class="greenline">
</section>
<footer id="footer">
    {% block extrafooter %}
    {% endblock extrafooter %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 footer-logo">
              <a href="//www.levantalamano.cl/" onclick="ga('send', 'event', 'footer-levantalamano', 'click')"><img src="{% static 'img/lm-footer-logo.svg' %}" alt="Levanta la mano"></a>
            </div>
            <div class="col-sm-6 col-md-2 footer-logo">
              <span class="small">En el marco de</span>
              <div><a href="//www.votainteligente.cl/" onclick="ga('send', 'event', 'footer-votainteligente', 'click')" target="_blank"><img src="{% static 'img/lm-footer-vota.svg' %}" alt="Vota Inteligente"></a></div>
            </div>
            <div class="col-sm-6 col-md-2 footer-logo">
              <span class="small">Organizado por</span>
              <div><a href="//www.ciudadanointeligente.org/" onclick="ga('send', 'event', 'footer-ciudadanoi', 'click')" target="_blank"><img src="{% static 'img/lm-footer-fci.svg' %}" alt="Ciudadano Inteligente"></a></div>
            </div>
            <div class="col-sm-6 col-md-2 footer-logo">
              <span class="small">Con el apoyo de</span>
              <div><a href="//www.unicef.cl/" onclick="ga('send', 'event', 'footer-unicef', 'click')" target="_blank"><img src="{% static 'img/lm-footer-unicef.svg' %}" alt="Unicef para cada niño"></a></div>
            </div>
            <div class="col-sm-6 col-md-2 footer-logo">
              <span class="small">Con el patrocinio de</span>
              <div><a href="//www.mineduc.cl/" onclick="ga('send', 'event', 'footer-mineduc', 'click')" target="_blank"><img src="{% static 'img/lm-footer-mineduc.svg' %}" alt="Ministerio de Educación"></a></div>
            </div>
        </div>
    </div>
</footer>

votai_general_theme/templates/votita/agregar_propuestas_a_encuentro.html
{% extends "votita/base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block content %}
<div class="container">
  <h2 class="h-header">Elaboración de programa de {{object.name}}</h2>
  <form method="post" action="{% url 'votita:proposal_for_gathering' pk=object.pk %}">
    {% csrf_token %}
    {{formset.management_form}}
    <div id="proposals-container">
      {% for form in formset.forms %}
      <h3 class="theme-form">Propuesta {{forloop.counter}}</h3>
      <fieldset class="proposals-fieldset-{{forloop.counter}}">
        {% bootstrap_form form  layout='inline' %}
      </fieldset>
      {% endfor %}
    </div>

    <script type="text/html" id="proposals-template">
      <p>Propuesta __prefix__</p>
      <fieldset class="proposals-fieldset-__prefix__" style="display: none;">
          {% bootstrap_form formset.empty_form  layout='inline' %}
      </fieldset>
    </script>
    <div>
      <button id="add-proposal" type="button" class="btn btn-agregar pull-left">Agregar más propuestas</button>
    </div>
    <input type="submit" value="{% trans "Enviar" %}"  class="btn btn-enviar pull-right" />
  </form>
</div>
<script>
$(function(){
  $('#add-proposal').djangoInlineFormAdd({
    prefix: "proposals",
    deleteButtonId: "delete-proposal"
  });
});
</script>
{% endblock content %}

votai_general_theme/templates/votita/card.html
{% load staticfiles %}
{% load votainteligente_extras %}
{% load i18n %}
{% load thumbnail %}
{% load cache %}
<!--InicioCard-->
<div class="post propuesta votita-love-{{proposal.clasification}}">
<!-- Hola Liss esta es la tarjeta de las propuestas del votita, se verán en el vota igual-->
  <div class="propuesta-content">
    {% cache 600 classification proposal.id  %}
    <span class="label label-default">{{proposal.get_classification}}</span>
    {% endcache %}
    <!-- Estado de una propuesta para el alcalde de esa comuna -->
    <div class="pull-right">
      {% include 'popular_proposal/_estado_para_candidato.html' with proposal=proposal next_url=popular_proposals_home %}
    </div>
    {% cache 600 gathering_name proposal.id  %}
    <div class="group">Propuesta de
      {{ proposal.gathering.name }}
    </div>
    {% endcache %}
    <h4><a href="{{proposal.get_absolute_url}}">{{proposal.title|truncatechars:100 }}</a></h4>
    <p class="intro">{{proposal.data.solution_at_the_end|linebreaksbr|truncatechars:150}}</p>
  </div>
  <div class="share-card">
    <hr>
      {% url 'popular_proposals:home' as popular_proposals_home %}
      {% include 'popular_proposal/_likers.html' with proposal=proposal area=area next_url=popular_proposals_home  support_button_extra_class="pull-left" %}
    {% comment %}
    <div class="share">
      {% include 'popular_proposal/_share.html' with popular_proposal=proposal %}
    </div>
    {% endcomment %}
    <a href="{{ proposal.get_absolute_url }}" class="btn btn-blue pull-right">Leer más</a>
  </div>
</div>
<!--FinCard-->

votai_general_theme/templates/votita/detalle_propuesta.html
{% extends "votita/base.html" %}

{% load votainteligente_extras %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load bootstrap3 %}
{% block extrajs %}
{% load ogp_tags %}
{% load cache %}


$(function(){
    $('.loadFromUrl').on('show.bs.modal', function (event) {
      var anchor = $(event.relatedTarget) // Button that triggered the modal
      var modal = $(this)
      var body = modal.find('.modal-body');
      body.load(anchor.data('url'));
    })
    $('[data-toggle="tooltip"]').tooltip();
});
{% endblock extrajs %}

{% block title %}- Propuesta - {{proposal.title}}{% endblock title%}

{% block ogp %}
  <meta property="og:title" content="Levanta La Mano">
  <meta property="og:type" content="website">
  <meta property="og:url" content="http://levantalamano.cl{{ proposal.get_absolute_url }}">
  <meta property="og:image" content="{{proposal.ogp_image}}">
  <meta property="og:description" content="{{proposal.data.solution}}">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@ciudadanoi">
  <meta name="twitter:creator" content="{% spaceless %}
  {% if proposal.proposer.profile.is_organization and proposal.proposer.organization_template.twitter %}
    {{proposal.proposer.organization_template.twitter|extract_twitter_username}}
  {% else %}
    @ciudadanoi
  {% endif %}
  {% endspaceless %}">
  <meta name="twitter:title" content="¡Ingresa a votainteligente.cl y apoya esta propuesta!">
  <meta name="twitter:description" content="{% spaceless %}
  {% if proposal.proposer.profile.is_organization and proposal.proposer.organization_template.twitter %}
  {{proposal.proposer.organization_template.twitter|extract_twitter_username}} propone {{ proposal.title }}
  {% else %}
  {{ proposal.title }}
  {% endif %}
  {% endspaceless %}">
  <meta name="twitter:image" content="{{proposal.ogp_image}}">
{% endblock ogp %}

{% block content %}

<section class="votita-love-detail-{{proposal.clasification}} votita-detail">
  <div class="container">
    <div class="row h-header">
      <div class="container print_hidden">
        <ol class="breadcrumb">
          <li><a href="{% url 'home' %}"><i class="fa fa-home" aria-label="Inicio"></i></a></li>
          <li><a href="{% url 'votita:list_proposals' %}">Propuestas</a></li>
          <li class="active">{{proposal.title}}</li>
        </ol>
      </div>
      <div class="col-md-9">
        <span class="label label-default">{{proposal.get_classification}}</span>
        <p class="group">
            Propuesta de {{proposal.gathering.name}}
        </p>
        <h1>{{proposal.title}}</h1>
        <ul class="list-inline proposal-tools">
          <li class="hidden-xs hidden-sm">
            <i class="fa fa-print" onclick="print()"></i>
          </li>
          <li>
            <i class="fa fa-font"></i>
          </li>
          <li>
            <i class="fa fa-plus" onclick="UpSize(2)"></i>
          </li>
          <li>
            <i class="fa fa-minus" onclick="DownSize(2)"></i>
          </li>
        </ul>
        <div class="line-space"></div>
        <script>
          function UpSize(size) {
            var fontSizeMax = 20;
            var FontSizeActual = parseInt($('#proposal-details p').css('font-size'));
            var fontNewSize = FontSizeActual+size;
            if(fontNewSize <= fontSizeMax)
              $('#proposal-details p').css('font-size', fontNewSize+'px');
          }
          function DownSize(size) {
            var fontSizeMin = 14;
            var FontSizeActual = parseInt($('#proposal-details p').css('font-size'));
            var fontNewSize = FontSizeActual-size;
            if(fontNewSize >= fontSizeMin)
              $('#proposal-details p').css('font-size', fontNewSize+'px');
          }
        </script>

        <!-- detalle propueta -->
        {{proposal.detail_as_html}}
        <!-- fin detalle propuesta -->

        <div class="modal fade" id="terms_and_conditions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Términos y Condiciones</h4>
              </div>
              <div class="modal-body">
                {% include 'popular_proposal/terms_and_conditions.html' %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <script>
         $(document).ready(function(){
            $('.reportar_propuesta').attr('href','mailto:'+'vota-2017'+'@'+'ciudadanointeligente.org?'+'Subject=Propuesta {{proposal.id}} no debe estar en Votainteligente'+ '&body=La propuesta con título {{proposal.title}} cuyo id es {{proposal.id}} NO debe estar en la plataforma VotaInteligente.cl por ...\n La propuesta la pueden visitar en https://votainteligente.cl{{proposal.get_absolute_url}}');
         })
        </script>
      </div><!-- col-md-9 -->

      <div class="col-md-3 text-center print_hidden votita-detail share-detail">
        <label>Apoya esta propuesta</label>
        <p class="apoyo-ciudadano">Esta propuesta tiene <span id='likers_count_{{proposal.id}}' class="conteo">{{proposal.likers.count}} <i class="fa fa-heart blue-light-txt" aria-hidden="true"></i></span> apoyo(s)</p>
        <div>
          {% include 'popular_proposal/_likers.html' with proposal=proposal next_url=request.path  avoid_counter=True %}
        </div>
        <hr>
        <label>Comparte esta propuesta</label>
        <div>
          {% include 'popular_proposal/_share.html' with popular_proposal=proposal next_url=request.path %}
        </div>
        {% if proposal.sponsoring_orgs.exists %}
        <hr>
          <label>Organizaciones que apoyan esta propuesta</label>
          <ul class="list-inline">
            {% for org in proposal.sponsoring_orgs %}
            <li>
              <a href="{% url 'organization_profiles:home' slug=org.username %}" target="_blank">
                {% cache 600 organization_logo org.id %}
                {% if org.organization_template.logo %}
                    {% thumbnail org.organization_template.logo "300x300" crop="center" as im %}
                    <a href="{{org.organization_template.get_absolute_url}}">
                      <img src="{{im.url}}" alt="{{org.organization_template.title }}" title="{{org.organization_template.title }}" border="0" class="img-responsive img-circle img-candidato-small">
                    </a>
                    {% endthumbnail %}
                  {% else %}
                    <img src="{% static 'img/org-default.png' %}" alt="{{org.organization_template.title }}" title="{{org.organization_template.title }}" class="img-responsive img-circle img-candidato-small"></a>
                {% endif %}
                {% endcache %}
              </a>
            </li>
            {% endfor %}
          </ul>

          {% endif %}
          {% include 'popular_proposal/_likers_candidatos.html' with proposal=proposal cargo='Presidenta o Presidente'%}
          {% include 'popular_proposal/_likers_candidatos.html' with proposal=proposal cargo='Senadora o Senador'%}
          {% include 'popular_proposal/_likers_candidatos.html' with proposal=proposal cargo='Diputada o Diputado'%}

      </div><!-- col-md-3 -->
    </div><!-- row -->
  </div><!-- container -->
</section>

{% include "votita/gathering_detail.html" with gathering=proposal.gathering %}

{% with "supportProposal"|add:proposal.slug as modalid %}
  {% include 'modal_like_proposal.html' with modalId=modalid title='Apoya una propuesta' url=like_this_proposal_url next_url=request.path proposal=proposal %}
{% endwith %}

{% endblock content %}

{% block extrafooter %}
{% endblock extrafooter %}

votai_general_theme/templates/votita/encuentro_card.html
<li><a href="{% url 'votita:ver_encuentro' encuentro.pk %}">{{encuentro.name}}</a></li>

votai_general_theme/templates/votita/lista_encuentros.html
{% extends "votita/base.html" %}

{% block title %}- Lista de encuentros{% endblock title %}

{% block content %}
<div class="container">
  <h1 class="page-header">Lista de encuentros infantiles/juveniles</h1>
  <ul>
  {% for encuentro in gatherings %}
    {% include 'votita/encuentro_card.html' with encuentro=encuentro %}
  {% endfor %}
  </ul>
</div>
{% endblock content %}

votai_general_theme/templates/votita/view_gathering_detail.html
{% extends "votita/base.html" %}
{% load bootstrap3 %}

{% block title %}- Ver encuentro - {{object.name}}{% endblock title %}

{% block content %}

{% include "votita/gathering_detail.html" with gathering=object %}
{% endblock content %}