elections/urls.py
from django.conf import settings
from django.conf.urls import url
from haystack.views import SearchView
from elections.forms import ElectionForm
from elections.views import (
    ElectionsSearchByTagView,
    HomeView,
    ElectionDetailView,
    CandidateDetailView,
    FaceToFaceView,
    AreaDetailView,
    CandidateFlatPageDetailView,
    KnowYourCandidatesView,
    )

from elections.soul_mate import SoulMateDetailView

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.cache import cache_page


media_root = getattr(settings, 'MEDIA_ROOT', '/')




urlpatterns = [
    url(r'^$', cache_page(60 * settings.CACHE_MINUTES)(xframe_options_exempt(HomeView.as_view())), name='home'),
    url(r'^buscar/?$', SearchView(template='search.html',
            form_class=ElectionForm), name='search'),
    url(r'^busqueda_tags/?$', ElectionsSearchByTagView.as_view(), name='tags_search'),
    url(r'^eleccion/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_detail.html')),
        name='election_view'),
    url(r'^eleccion/(?P<slug>[-\w]+)/questionary/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/election_questionary.html')),
        name='questionary_detail_view'),
    #compare two candidates
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/(?P<slug_candidate_two>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(FaceToFaceView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_two_candidates_detail_view'),
    #one candidate for compare
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/(?P<slug_candidate_one>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_one_candidate_detail_view'),
    #no one candidate
    url(r'^eleccion/(?P<slug>[-\w]+)/face-to-face/?$',
        cache_page(60 * settings.CACHE_MINUTES)(ElectionDetailView.as_view(template_name='elections/compare_candidates.html')),
        name='face_to_face_no_candidate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/soul-mate/?$',
        csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html')),
        name='soul_mate_detail_view'),
    #soulmate
    url(r'^eleccion/(?P<slug>[-\w]+)/embedded-soul-mate/?$',
        xframe_options_exempt(csrf_exempt(SoulMateDetailView.as_view(template_name='elections/soulmate_candidate.html', layout="elections/embedded.html"))),
        name='embedded_soul_mate_detail_view'),

    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view'
        ),
    url(r'^candidaturas/(?P<area_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateDetailView.as_view(template_name='elections/candidate_detail.html')),
        name='candidate_detail_view_area'
        ),
    # End Preguntales
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<url>[-\w]+)/?$',
        cache_page(60 * settings.CACHE_MINUTES)(CandidateFlatPageDetailView.as_view()),
        name='candidate_flatpage'
        ),
    url(r'^eleccion/(?P<slug>[-\w]+)/extra_info.html$',
        ElectionDetailView.as_view(template_name='elections/extra_info.html'),
        name='election_extra_info'),
    url(r'^candidaturas/(?P<slug>[-\w]+)/?$',
        AreaDetailView.as_view(template_name='elections/area.html'),
        name='area'),
    url(r'^ayudanos/(?P<slug>[-\w]+)/?$',
        ElectionDetailView.as_view(template_name='elections/ayudanos.html'),
        name='help_election'),
    url(r'^candidaturas/?$', KnowYourCandidatesView.as_view(), name='know_your_candidates'),
    
]

# urlpatterns += [
#     url(r'^cache/(?P<path>.*)$', sitemap,
#         {'document_root': media_root})
# ]

medianaranja2/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from medianaranja2.views import (ShareYourResult,
                                 ShareMyResultPlz,
                                 ShareMyResultOrgPlz,
                                 SharedResultOGImageView,
                                 get_medianaranja_view)
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^$',
        get_medianaranja_view,
        name='index'),
    url(_(r'^compartir/?$'),
        ShareMyResultPlz.as_view(),
        name='create_share'),
    
    url(_(r'^compartir_org/?$'),
        ShareMyResultOrgPlz.as_view(),
        name='create_share_org'),
    url(_(r'^compartir/(?P<identifier>[-\w]+)/?$'),
        ShareYourResult.as_view(),
        name='share'),
    url(_(r'^og_image/(?P<identifier>[-\w]+).jpg$'),
        SharedResultOGImageView.as_view(),
        name='og_image'),
]
if settings.DEBUG:# pragma: no cover
    from medianaranja2.forms import MediaNaranjaResultONLYFORDEBUG
    urlpatterns += [
        url(r'^medianaranja2_resultado/$', MediaNaranjaResultONLYFORDEBUG.as_view(),
        name='medianaranja2_resultado')
    ]

merepresenta/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView, RedirectView
from merepresenta.forms import (MeRepresentaMeiaLaranjaWizardForm,
                                MeRepresentaMeiaLaranjaQuestionsWizardForm)
from elections.views import CandidateDetailView
from elections.models import QuestionCategory
from django.contrib import admin
from backend_candidate.views import CompleteMediaNaranjaView
from backend_candidate.forms import MediaNaranjaElectionForm
from merepresenta.voluntarios.views import (VolunteerIndexView,
                                            VolunteerLoginView,
                                            AddMailToCandidateView,
                                            ObrigadoView,
                                            auth,
                                            CouldNotFindCandidate,
                                            FacebookContacted,
                                            complete)
from merepresenta.match.views import MatchView, MatchResultView, MatchResultAjaxView
from merepresenta.views import ColigacoesPerAreaView, ColigacoesInitialRedirect

class MeRepresentaMeiaLaranjaForm(MediaNaranjaElectionForm):
    def __init__(self, *args, **kwargs):
        self.categories  = QuestionCategory.objects.all()
        super(MeRepresentaMeiaLaranjaForm, self).__init__(*args, **kwargs)

class MeRepresentaMeiaLaranja(CompleteMediaNaranjaView):
    def get_form_class(self):
        return MeRepresentaMeiaLaranjaForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',
        TemplateView.as_view(template_name="merepresenta/index.html"),
        name='index'),

    url(r'^sobre/?$',
        TemplateView.as_view(template_name="merepresenta/sobre.html"),
        name='sobre'),
    url(r'^eleitor/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitores/?$',
        RedirectView.as_view(url='/eleitora'),
        name='eleitor'),
    url(r'^eleitorx/?$',
        TemplateView.as_view(template_name='merepresenta/eleitor.html'),
        name='eleitorx'),
    url(r'^termos/?$',
        TemplateView.as_view(template_name="merepresenta/termos.html"),
        name='termos'),
    url(r'^pautas/?$',
        TemplateView.as_view(template_name="merepresenta/pautas.html"),
        name='pautas'),
    url(r'^coligacoes/?$',
        ColigacoesInitialRedirect.as_view(),
        name='coligacoes_initial'),
    url(r'^coligacoes/(?P<slug>[-\w]+)/?$',
        ColigacoesPerAreaView.as_view(),
        name='coligacoes'),
    url(r'^eleitora/?$',
        MatchView.as_view(),
        name='match'),
    url(r'^resultado/?$',
        MatchResultView.as_view(),
        name='match_result'),
    url(r'^match_result_ajax/?$',
        MatchResultAjaxView.as_view(),
        name='match_result_ajax'),




    url(r'^perguntas/?$',
        MeRepresentaMeiaLaranjaWizardForm.as_view(),
        name='questionary'),
    url(r'^answers/?$',
        MeRepresentaMeiaLaranjaQuestionsWizardForm.as_view(),
        name='questions'),
    url(r'^candidatos/', include('merepresenta.candidatos.urls')),
    url(r'^eleccion/(?P<election_slug>[-\w]+)/(?P<slug>[-\w]+)/?$',
        CandidateDetailView.as_view(template_name='merepresenta/candidate_detail.html'),
        name='candidate_detail_view'
        ),
    url(r'^candidatos/media_naranja/(?P<slug>[-\w]+)/(?P<candidate_slug>[-\w]+)/?$',
        MeRepresentaMeiaLaranja.as_view(),
        name='complete_12_naranja'),
    url(r'^candidatos/?', include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^accounts/?', include('registration.backends.hmac.urls')),
    url(r'^voluntarios/', include('merepresenta.voluntarios.urls')),
    url(r'^faq/?$',
    TemplateView.as_view(template_name="merepresenta/faq.html"),
    name='faq'),
]

rioxinteiro/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^interes_candidato/$',
        TemplateView.as_view(template_name='registro_interes_candidato.html'),
        name='interes_candidato'),
] 

votainteligente/urls.py
from django.conf.urls import include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from backend_candidate.views import HelpFindingCandidates
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_change, password_change_done, login
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from votainteligente.sitemaps  import ElectionsSitemap, CandidatesSitemap, ProposalSitemap
from votainteligente.rest_api_router import router
from django.utils.translation import ugettext_lazy as _
admin.autodiscover()
admin.site.site_header = getattr(settings, 'ADMIN_HEADER', 'Vota Inteligente')


sitemaps = {
    'elections': ElectionsSitemap,
    'candidates': CandidatesSitemap,
    'proposals': ProposalSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'votainteligente.views.home', name='home'),
    # url(r'^votainteligente/', include('votainteligente.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('elections.urls')),
    url(_(r'^preguntales/'), include('preguntales.urls')),
    url(_(r'^propuestas/'), include('popular_proposal.urls', namespace='popular_proposals')),
    url(_('^pages/'), include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backend_staff/', include('backend_staff.urls', namespace='backend_staff')),
    url(_(r'^perfil_ciudadano/'), include('backend_citizen.urls', namespace='backend_citizen')),
    url(r'^suggestions/', include('suggestions_for_candidates.urls', namespace='suggestions_for_candidates')),
    url(_(r'^media_naranja/'), include('medianaranja2.urls', namespace='medianaranja2')),
    url(_(r'^organizacion/'), include('organization_profiles.urls', namespace='organization_profiles')),
    url(_(r'^candidatos/'), include('backend_candidate.urls', namespace='backend_candidate')),
    url(r'^proposal_subscriptions/', include('proposal_subscriptions.urls', namespace='proposal_subscriptions')),
    url(r'^levantalamano/', include('votita.urls', namespace='votita')),
    url(r'^cuentas/', include('votita.urls.auth_urls', namespace="votita_auth")),
    url(_(r'^ayudanos/$'),
        HelpFindingCandidates.as_view(),
        name='help'),
    url(_(r'^encuentro_ciudadano/$'),
        TemplateView.as_view(template_name='encuentro_ciudadano.html'),
        name='encuentro_ciudadano'),
    url(_(r'^que_es/$'),
        TemplateView.as_view(template_name='que_es.html'),
        name='que_es'),
    url(_(r'^material_ciudadano/$'),
        TemplateView.as_view(template_name='material_ciudadano.html'),
        name='material_ciudadano'),
    url(r'^cores/$',
        TemplateView.as_view(template_name='cores.html'),
        name='cores'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/organizacion/?$',
        login,
        {'template_name': 'registration/login_organizacion.html'},
        name='login_users'),
    url(r'^accounts/login/usuario_y_password/?$',
        login,
        {'template_name': 'registration/login_username_and_password.html'},
        name='username_and_password'),
    url(r'^accounts/passwordchange/?$',
        password_change,
        {'template_name': 'registration/password_change.html'},
        name='password_reset'),
    url(r'^accounts/passwordchange/done/?$',
        password_change_done,
        {'template_name': 'registration/password_change_done_.html'},
        name='password_change_done'),
    url(r'^api/', include(router.urls)),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),

]

urlpatterns += [
                        url('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.THEME:
    urlpatterns += [
        url('^theme/', include('%s.urls' % (settings.THEME)))
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

rioxinteiro/forms.py
# coding=utf-8
from django import forms


class PersonalDataForm(forms.Form):
    lema = forms.CharField(label=u'Slogan da campanha', required=False, initial='')
    ocupacion = forms.CharField(label=u'Ocupação atual', required=False, initial='')
    raca = forms.CharField(label=u'Raça', required=False, initial='')
    orietacion_sexual = forms.CharField(label=u'Orientação sexual', required=False, initial='')
    territorio = forms.CharField(label=u'Território', required=False, initial='')
    experiencia = forms.CharField(label=u'Bio',
                                  widget=forms.Textarea(),
                                  max_length=4096,
                                  required=False,
                                  initial=''
                                  )
    telefono = forms.CharField(label=u'Número de telefone',
                               required=False,
                               initial='',
                               help_text=u"Existe um telefone onde os cidadãos interessados na sua campanha podem se comunicar com você?")

medianaranja2/views.py
from django.views.generic import DetailView
from medianaranja2.models import SharedResult
from django.contrib.contenttypes.models import ContentType
from elections.models import QuestionCategory
from elections.models import Candidate
from medianaranja2.forms import ShareForm
from django.views.generic.edit import CreateView
from organization_profiles.models import OrganizationTemplate
from django.http import HttpResponse
from medianaranja2.forms import MediaNaranjaOnlyProposals, MediaNaranjaWizardForm, MediaNaranjaNoQuestionsWizardForm



class ShareYourResult(DetailView):
    model = SharedResult
    slug_url_kwarg = 'identifier'
    slug_field = 'identifier'
    template_name = 'medianaranja2/comparte_resultado.html'

    def get_context_data(self, **kwargs):
        context = super(ShareYourResult, self).get_context_data(**kwargs)
        context['shared_object'] = self.object.data['object_id']
        context['percentage'] = self.object.data['percentage']
        return context


class ShareMyResultPlzBase(CreateView):
    form_class = ShareForm
    template_name = 'medianaranja2/create_share.html'

    def get_form_kwargs(self):
        kwargs = super(ShareMyResultPlzBase, self).get_form_kwargs()
        kwargs['content_type'] = ContentType.objects.get_for_model(self.shared_object_class)
        return kwargs

class ShareMyResultPlz(ShareMyResultPlzBase):
    shared_object_class = Candidate

class ShareMyResultOrgPlz(ShareMyResultPlzBase):
    shared_object_class = OrganizationTemplate


class SharedResultOGImageView(DetailView):
    model = SharedResult
    slug_url_kwarg = 'identifier'
    slug_field = 'identifier'

    def render_to_response(self, context, **response_kwargs):
        im = self.object.get_shared_image()
        response = HttpResponse( content_type="image/png")
        im.save(response, "PNG")
        return response

def get_medianaranja_view(*args, **kwargs):
    from django.conf import settings
    from constance import config
    if settings.MEDIA_NARANJA_QUESTIONS_ENABLED:
        if not QuestionCategory.objects.exists():
            view = MediaNaranjaNoQuestionsWizardForm.as_view()
        else:
            view = MediaNaranjaWizardForm.as_view()
    else:
        view = MediaNaranjaOnlyProposals.as_view()

    try:
        if config.PRUEBAS_DE_CARGA_MEDIA_NARANJA:
            view = csrf_exempt(view)
    except:
        pass
    return view(*args, **kwargs)

rioxinteiro/templates/medianaranja2/base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load votainteligente_extras %}
{% load cache %}
{% load bootstrap3 %}
{% block title %}- Tem Compromisso{% endblock title %}

{% block ogp %}
  <meta property="og:title" content="#TemCompromisso">
  <meta property="og:type" content="{{ config.WEBSITE_OGP_TYPE }}">
  <meta property="og:url" content="https://{% url_domain %}{% url 'medianaranja2:index' %}">
  <meta property="og:image" content="{% static 'img/compartilhar_tem_compromiso.png' %}">
  <meta property="og:description" content="Uma ferramenta para ajudar você a encontrar candidatos (as) comprometidos com o Rio!">
  <meta property="fb:app_id" content="201933520410976">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@CasaFluminense">
  <meta name="twitter:creator" content="@CasaFluminense">
  <meta name="twitter:title" content="#TemCompromisso">
  <meta name="twitter:description" content="Uma ferramenta para ajudar você a encontrar candidatos (as) comprometidos com o Rio!">
  <meta name="twitter:image" content="{% static 'img/compartilhar_tem_compromiso.png' %}">

  {% endblock ogp %}

{% block everything %}
<section class="media-naranja">
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <img src="{% static 'img/logo_tem_compromiso.svg' %}" class="img-responsive" alt="TemCompromiso">
    </div>
    <div class="col-md-5 col-md-offset-1 tem-compromisso-info">
      <h2>Estamos entrando na reta final de um dos momentos mais importantes do segundo semestre de 2018: você na urna!</h2>
      <p>Já parou pra pensar quais candidatos (as) estão de fato comprometidos em diminuir desigualdades e aumentar oportunidades na metrópole do rio? Tarefa nada fácil, né? Por isso, juntamos parte das nossas forças aqui!</p>
      <p>Depois de incentivar você a criar propostas para a cidade a partir da sua própria experiência com o território, criamos um jogo de perguntas para te conectar com as candidaturas que mais se relacionam com temas relevantes pra você!</p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 naranja-form">
      <div class="text-center paso_title">
      </div>
      {% block questions %}
      {% endblock questions %}
    </div>
  </div>
</div>
</section>
{% endblock everything %}

rioxinteiro/templates/medianaranja2/comparte_resultado.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load votainteligente_extras %}
{% load cache %}
{% load bootstrap3 %}
{% block title %}- {% blocktrans with step_number=wizard.steps.step1 %}
1/2 Naranja - Paso {{step_number}}
{% endblocktrans %}{% endblock title %}

{% block ogp %}
  <meta property="og:title" content="#TemCompromisso em RioPorInteiro">
  <meta property="og:type" content="{{ config.WEBSITE_OGP_TYPE }}">
  <meta property="og:url" content="https://{% url_domain %}{{object.get_absolute_url}}">
  <meta property="og:image" content="https:{{object.ogp_image }}">
  <meta property="og:description" content="{{object.object.get_name}} - #TemCompromisso em RioPorInteiro">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@CasaFluminense">
  <meta name="twitter:creator" content="{{object.object.twitter }}">
  <meta name="twitter:title" content="#TemCompromisso em RioPorInteiro">
  <meta name="twitter:description" content="{{object.object.get_name}} - #TemCompromisso em RioPorInteiro">
  <meta name="twitter:image" content="https:{{object.ogp_image }}">

  {% endblock ogp %}


{% block content %}
<div class="container">
  <h2>{% trans "Declaración pública" %}</h2>
  <p>
    Você também pode saber quem <a href="{% url 'medianaranja2:index' %}">#TemCompromisso</a>.
    </p>
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">

      <div class="panel panel-default">
        <div class="panel-body">
          <a href="{{object.object.get_absolute_url}}">
            <img src="{{object.ogp_image}}" class="img-responsive" alt="{{object.object.get_name}}" title="{{object.object.name}}">
          </a>
          <ul class="list-inline text-center">
            <li><a href="#" onclick="window.open('//twitter.com/share','twitter','width=450, height=250'); ga('send','event','share-media-naranja-tw','click')"><i class="fa fa-twitter fa-2x"></i></a></li>
            <li><a href="#" onclick="window.open('//www.facebook.com/sharer/sharer.php','facebook','width=450, height=250'); ga('send','event','share-media-naranja-fb','click');"><i class="fa fa-facebook fa-2x"></i></a></li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

rioxinteiro/templates/medianaranja2/resultado.html
{% extends "medianaranja2/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load votainteligente_extras %}
{% load cache %}
{% load bootstrap3 %}
{% block title %}- Tem Compromisso{% endblock title %}



{% block paso %}
<h1>{% trans "Resultados" %}</h1>
{% endblock paso %}

{% block questions %}
{% if organizations.exists %}
<div class="col-md-12">
<p class='exp_orgs'>Suas prioridades no #TemCompromisso são conduzidas diariamente por essas organizações da Rio por Inteiro. 
Convidamos você a conhecê-las e se juntar às causas que te interessam!</p>
  <h3>{% trans "Organizaciones" %}</h3>
    {% for o in organizations.all %}
    {% cache 83000 organization_in_result_ o.id %}
    <div class="col-md-4 text-center">
        {% if o.logo_small %}
        <a href="{{o.get_absolute_url}}"><img src="{{o.logo_small.url}}" alt="{{o.title}}" title="{{o.title}}" height="96" width="96" border="0" class="img-circle"></img></a>
        {% endif %}
        <ul class="list-unstyled list-inline">
          {% if o.org_url %}
          <li><a href="{{o.org_url}}"><i class="fa fa-globe" aria-label="Website"></i></a></li>
          {% endif %}
          {% if o.facebook %}
          <li><a href="{{o.facebook}}"><i class="fa fa-facebook" aria-label="Facebook"></i></a></li>
          {% endif %}
          {% if o.twitter %}
          <li><a href="{{o.twitter}}"><i class="fa fa-twitter" aria-label="Twitter"></i></a></li>
          {% endif %}
          {% if o.instagram %}
          <li><a href="{{o.instagram}}"><i class="fa fa-instagram" aria-label="Instagram"></i></a></li>
          {% endif %}
          {% if o.rss_url %}
          <li><a href="{{o.rss_url}}"><i class="fa fa-rss" aria-label="RSS"></i></a></li>
          {% endif %}
        </ul>
      <div>
        <form action="{% url 'medianaranja2:create_share_org' %}" method="POST"  target="_blank">
          {% csrf_token %}
          <input name='object_id' type="hidden" value="{{ o.id }}"/>

          <!-- <input type="submit" value="Compartilhar"  class="btn btn-default" /> -->

        </form>
        </div>
    </div>
    {% endcache %}
    {% endfor %}
</div>
<hr>
{% endif %}


{% for election_result in results %}
<div class="col-md-12">
  <h3>{% blocktrans with election_name=election_result.election.name %}
    Suas candidaturas para {{election_name}} são
  {% endblocktrans %}</h3>
  {% for candidate_result in election_result.candidates %}
  <div class="col-md-4 text-center">
      <div class="text-center candidate-result-value">{{ candidate_result.value|floatformat }}%</div>
      {% cache 83000 candidate_result_numero candidate_result.candidate.id %}
      <a href="{{candidate_result.candidate.get_absolute_url}}">
      {% if candidate_result.candidate.image %}
        {% thumbnail candidate_result.candidate.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" alt="{{candidate_result.candidate.name}}" height="96" width="96" border="0" class="img-circle">
        {% endthumbnail %}
      {% else %}
        <img src="{% static 'img/candidate-default.jpg' %}" alt="{{candidate_result.candidate.name}}" height="96" width="96" border="0" class="img-circle">
      {% endif %}
      </a>
      <p class="candidate-result-name"><a href="{{candidate_result.candidate.get_absolute_url}}">{{candidate_result.candidate}}</a></p>
        {% get_personal_data candidate=candidate_result.candidate personal_data='Numero' as numero %}
        {% if numero.value %}
        <div><span class="label-default">{{numero.value}}</span></div>
        {% endif %}
        {% endcache %}

        <div>
        <form action="{% url 'medianaranja2:create_share' %}" method="POST"  target="_blank">
          {% csrf_token %}
          <input name='object_id' type="hidden" value="{{ candidate_result.candidate.id }}"/>
          <input name="percentage" type="hidden" value="{{ candidate_result.value|floatformat:0 }}" />

          <!-- <input type="submit" value="Compartilhe"  class="btn btn-default" /> -->

        </form>
        </div>
    </div>
  {% endfor %}
</div>
<hr>
{% endfor %}

<a href="{% url 'medianaranja2:index' %}" class="btn btn-success pull-right" role="button" onclick="ga('send','event','juega-de-nuevo','click')">{% trans "Juega de nuevo" %}</a>
{% endblock questions %}